# Generated by Django 4.0.6 on 2022-07-28 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FloatField()),
                ('description', models.CharField(max_length=40)),
                ('date', models.DateField()),
            ],
        ),
    ]
